### ISSUE TITLE
Repo has no code

### ISSUE THREAD

**Issue by HDVinnie** [GaryCornell/Laravel-5.4x-Private-Messenger#2]
The repo has no code.

## Expected Behavior
I open the repo and see the code.

## Current Behavior
I open the repo and see no code.

## Possible Solution
Upload code.

## Steps to Reproduce (for bugs)
Live example: https://github.com/GaalexxC/LaraPM
1. Visit repo
2. Observe lack of code

**Comment by GaalexxC** [comment]
Sorry been busy on other projects and haven't had the chance to get this updated. I will try and have the code up by the weekend.

**Comment by HDVinnie** [comment]
Thanks....looks very interesting and looking forward to checking out the code.

**Comment by HDVinnie** [comment]
any update?

**Comment by HDVinnie** [comment]
You should really close this repo....7 months and still zero code.

**Comment by GaalexxC** [comment]
Why should I close it? There are thousands of repos here that are incomplete. I'm sorry I haven't had the time Vinnie, a week of flu and several other projects just been too busy. I am currently under a time constraint for the BitTracker project,: https://github.com/GaalexxC/IPS-4.2-BitTracker

Once I get that into working Beta (Week or less) I will be more then Happy to get this going here. Its been awhile so I will need to update my code and Laravel version but I will get it buddy just bear with me.

**Comment by HDVinnie** [comment]
close was wrong word.....you should use the archive option until your ready to release. 7 months is awhile with not code produced you must admit this?

**Comment by GaalexxC** [comment]
I can agree with that. When I added the repo I had the time and then stuff came up, this and that, just never got around to it. Maybe I can make some time this weekend, the current project I am working on his almost complete on the framework side so might get a few hours to revisit this in the next few days.
